### ISSUE TITLE
Consider adding HTTPoison options to unfurl/1

### ISSUE THREAD

**Issue by abitdodgy** [claytongentry/furlex#10]
It's not unsual to want to connect to a url with options. For exmaple, you may want to set the number of tries or connect through a proxy.

**Comment by claytongentry** [comment]
What do you think about this @abitdodgy? https://github.com/claytongentry/furlex/pull/12

**Comment by abitdodgy** [comment]
I think that should do it too. It's essentially what I did on my fork. Sorry, I should be submitting pull requests for these, but since I'm moving at the speed of light, I'm not taking the time to write tests to verify my work beyond the basics.

**Comment by claytongentry** [comment]
All good, appreciate you raising these issues nonetheless! Merged that PR above.
