### ISSUE TITLE
Make JSON lib configurable

### ISSUE THREAD

**Issue by abitdodgy** [claytongentry/furlex#21]
Would you be interested in a pull request that made the JSON lib configurable? For example, say you want to use Jason instead of Poison.

**Comment by claytongentry** [comment]
Absolutely! In fact, would you mind just swapping it out? We could default to Jason and let people configure Poison if they wanted.

**Comment by claytongentry** [comment]
Ah nice, just now seeing your PR. Great minds! 🤘

**Comment by claytongentry** [comment]
Thanks again! 🏅Included in [0.4.1](https://hex.pm/packages/furlex/0.4.1)
