### ISSUE TITLE
depth: :flat config option doesn't seem to do anything

### ISSUE THREAD

**Issue by abitdodgy** [claytongentry/furlex#9]
I added the option to the config as shown in the readme, but it appears to be ignored (in Phoenix 1.3 at least)

**Comment by claytongentry** [comment]
You're right. I believe I was being a little over-explicit when I wrote that. I'll take care.

**Comment by claytongentry** [comment]
This should do it, I think: https://github.com/claytongentry/furlex/pull/11. Thanks!
